### PR TITLE
Added optional transform function invoked prior to encoding

### PR DESCRIPTION
**Pull request by nickplee**
I noticed that one of our apps (which uses Mongoose as an ORM) was outputting some strange data. Turns out that `msgpack-lite` was serializing all sorts of internal properties on the Mongoose objects.

This recursively traverses an object and cleans it up as appropriate before the response is encoded.

### CODE REVIEW

**Comment by kfitzgerald** [comment]
Hi @nickplee!

Thanks for the PR! 

I’ve fallen victim to the Mongoose objects in the past too. Mongoose models have a `.toObject()` function to return a clean object, useful for serialization. I suppose updating your app routes to force a clean object out would be out of the question?

Let me do some research to see if there are other hapi plugins that do similar functionality and how they might deal with it. I’m not opposed to your contribution though!

I’ll look into it shortly.

Thanks again!

**Comment by nickplee** [comment]
Nope, not opposed to that, would just be a lot of repeated code all over the app. Maybe the solution is to have an intermediate transformer that cleans up the response before it hits this plugin. I don't know a ton about the `hapi` plugin architecture but sounds like it should be possible. 

My reasoning was that `hapi`, by virtue of calling `JSON.stringify` on the responses, does this automatically, so changing the content type to `application/x-msgpack` actually yields inconsistent responses.

Btw, thank you for making this lib!

**Comment by kfitzgerald** [comment]
Hi @nickplee !

I had a chat in the Hapi slack about best practices on this topic, and we're in consensus that this sort of thing may end up to be a slippery slope.

My proposal is that we add a plugin option to accept a pre-encode hook function, to allow you to configure the plugin to handle Mongoose models special, as well as enabling similar use-cases with other ORM models or special objects. 

I think that would keep the plugin "pure" while still easily enabling the app to do special encode-time handing of special objects, without having to worry about "did i forgot just one last return point?"

Would that sound good? 

I have a couple errands to run but should have some time to quick tackle it this afternoon. 

Thanks again – Glad you like the lib!
-Kevin

**Comment by nickplee** [comment]
Yes, that makes total sense to me.

**Comment by kfitzgerald** [comment]
Hi @nickplee !

I've implemented an option in both branches that should meet your needs:

For example:
```js
const server = new Hapi.Server();
const plugin = {
    plugin: require('hapi-msgpack'),
    options: {
        mimeType: 'application/x-msgpack',
        preEncode: (payload) => { return payload; } 
    }
};
```

Published to npm as:
 * 1.1.0 (hapi-16 and under)
 * 2.1.0 (hapi-17 and up)

Let me know if this works for you.

Thanks again,
-Kevin

**Comment by kfitzgerald** [comment]
Oh @nickplee, just noticed you updated your branch with basically this exact change, diff function name. Sorry.. woulda gone with yours if I had seen it.

**Comment by kfitzgerald** [comment]
Hey @nickplee – Have you had a chance to try v2.1.0? (or v1.1.0 if below hapi-16)

Thanks,
-Kevin

**Comment by nickplee** [comment]
Yes! Works as expected. Closing this.

**Comment by kfitzgerald** [comment]
@nickplee Glad to hear! Thanks again.

**Pull request closed without merging**
